version: '2'
services:
  postgres:
    image: postgres:10.3
    container_name: nest-db-postgres
    volumes:
      - ./database/volumes/postgree:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=ideas
      - POSTGRES_DB=ideas
      - POSTGRES_USER=ideas
  app:
    image: node:carbon
    container_name: nest-ideas-app
    working_dir: /usr/src/app
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    links:
      - postgres
